image: atlassian/default-image:2
definitions:
  steps:
    - step:
        script: &start-build |-
          apk add --no-cache curl &&
          curl -sLO "https://github.com/argoproj/argo-workflows/releases/download/v3.5.0/argo-linux-amd64.gz" &&
          gunzip "argo-linux-amd64.gz" &&
          chmod +x argo-linux-amd64 &&
          mv ./argo-linux-amd64 /usr/local/bin/argo &&
          echo $KUBECONFIG_B64 | base64 -d > /kubeconfig &&
          export KUBECONFIG=/kubeconfig
    - step:
        script: &submit-workflow |-
          ARGO_JOBNAME=$(argo -n argo submit \
            --from workflowtemplate/buildah-https-workflow-template \
            --name "${BITBUCKET_REPO_SLUG}-${BRANCH}-${BITBUCKET_BUILD_NUMBER}" \
            -p dockerImage="${BITBUCKET_REPO_SLUG}" \
            -p gitRepo="bitbucket.org/${BITBUCKET_REPO_FULL_NAME}.git" \
            -p gitRevision="${BITBUCKET_BRANCH}" \
            -p helmChartPath="deploy" \
            -p chartVersion="${CHART_VERSION}" \
            --output name)
    - step:
        script: &finish-build |-
          argo -n argo logs --follow "${ARGO_JOBNAME}" &&
          argo -n argo watch "${ARGO_JOBNAME}" &&
          argo -n argo wait "${ARGO_JOBNAME}"

pipelines:
  branches:
    deep:
      - step:
          name: Submit argo workflow
          image: atlassian/pipelines-kubectl
          script:
            - export CHART_VERSION="1.0.${BITBUCKET_BUILD_NUMBER}"
            - export BRANCH="master"
            - *start-build
            - *submit-workflow
            - *finish-build
    deep_dev:
      - step:
          name: Submit argo workflow
          image: atlassian/pipelines-kubectl
          script:
            - export CHART_VERSION="0.0.${BITBUCKET_BUILD_NUMBER}"
            - export BRANCH="dev"
            - *start-build
            - *submit-workflow
            - *finish-build